In [1]:
import numpy as np
from sklearn import preprocessing
from matplotlib import pyplot as plt
import glob
import os
from keras.layers import Input, Dense
from keras.models import Model

Using TensorFlow backend.


In [2]:
main = np.zeros([2995, 0], float)

print(main)
print(main.shape)
print(main.dtype)


[]
(2995, 0)
float64


In [3]:
#Import all the data into a single numpy array. Takes a while.
for file in os.listdir("E:\\Development Project\\Data\\GNPS Binned"):
     if file.endswith(".txt"):
            print(file)
            min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
            filepath = os.path.join("E:\\Development Project\\Data\\GNPS Binned", file)
            temp = np.loadtxt(filepath, np.float64, usecols = 2)
            temp = temp[:, np.newaxis]
            temp = min_max_scaler.fit_transform(temp)
            main = np.concatenate([main, temp], axis=1)

print("Done")

CCMSLIB00000001548 binned.txt
CCMSLIB00000001549 binned.txt
CCMSLIB00000001550 binned.txt
CCMSLIB00000001555 binned.txt
CCMSLIB00000001563 binned.txt
CCMSLIB00000001565 binned.txt
CCMSLIB00000001566 binned.txt
CCMSLIB00000001568 binned.txt
CCMSLIB00000001569 binned.txt
CCMSLIB00000001570 binned.txt
CCMSLIB00000001572 binned.txt
CCMSLIB00000001574 binned.txt
CCMSLIB00000001576 binned.txt
CCMSLIB00000001581 binned.txt
CCMSLIB00000001590 binned.txt
CCMSLIB00000001598 binned.txt
CCMSLIB00000001600 binned.txt
CCMSLIB00000001601 binned.txt
CCMSLIB00000001602 binned.txt
CCMSLIB00000001603 binned.txt
CCMSLIB00000001604 binned.txt
CCMSLIB00000001606 binned.txt
CCMSLIB00000001607 binned.txt
CCMSLIB00000001608 binned.txt
CCMSLIB00000001609 binned.txt
CCMSLIB00000001615 binned.txt
CCMSLIB00000001616 binned.txt
CCMSLIB00000001617 binned.txt
CCMSLIB00000001621 binned.txt
CCMSLIB00000001622 binned.txt
CCMSLIB00000001623 binned.txt
CCMSLIB00000001624 binned.txt
CCMSLIB00000001625 binned.txt
CCMSLIB000

CCMSLIB00000005421 binned.txt
CCMSLIB00000005430 binned.txt
CCMSLIB00000005433 binned.txt
CCMSLIB00000005436 binned.txt
CCMSLIB00000005439 binned.txt
CCMSLIB00000005445 binned.txt
CCMSLIB00000005448 binned.txt
CCMSLIB00000005451 binned.txt
CCMSLIB00000005454 binned.txt
CCMSLIB00000005469 binned.txt
CCMSLIB00000005472 binned.txt
CCMSLIB00000005478 binned.txt
CCMSLIB00000005481 binned.txt
CCMSLIB00000005496 binned.txt
CCMSLIB00000005502 binned.txt
CCMSLIB00000005505 binned.txt
CCMSLIB00000005508 binned.txt
CCMSLIB00000005514 binned.txt
CCMSLIB00000005523 binned.txt
CCMSLIB00000005526 binned.txt
CCMSLIB00000005529 binned.txt
CCMSLIB00000005532 binned.txt
CCMSLIB00000005538 binned.txt
CCMSLIB00000005541 binned.txt
CCMSLIB00000005544 binned.txt
CCMSLIB00000005547 binned.txt
CCMSLIB00000005556 binned.txt
CCMSLIB00000005568 binned.txt
CCMSLIB00000005580 binned.txt
CCMSLIB00000005583 binned.txt
CCMSLIB00000005589 binned.txt
CCMSLIB00000005595 binned.txt
CCMSLIB00000005598 binned.txt
CCMSLIB000

CCMSLIB00000070256 binned.txt
CCMSLIB00000070257 binned.txt
CCMSLIB00000070258 binned.txt
CCMSLIB00000070259 binned.txt
CCMSLIB00000070260 binned.txt
CCMSLIB00000070261 binned.txt
CCMSLIB00000070262 binned.txt
CCMSLIB00000070263 binned.txt
CCMSLIB00000070265 binned.txt
CCMSLIB00000070266 binned.txt
CCMSLIB00000070267 binned.txt
CCMSLIB00000070268 binned.txt
CCMSLIB00000070269 binned.txt
CCMSLIB00000070270 binned.txt
CCMSLIB00000070271 binned.txt
CCMSLIB00000070272 binned.txt
CCMSLIB00000070274 binned.txt
CCMSLIB00000070275 binned.txt
CCMSLIB00000070276 binned.txt
CCMSLIB00000070277 binned.txt
CCMSLIB00000070278 binned.txt
CCMSLIB00000070279 binned.txt
CCMSLIB00000070282 binned.txt
CCMSLIB00000070283 binned.txt
CCMSLIB00000070285 binned.txt
CCMSLIB00000070287 binned.txt
CCMSLIB00000070288 binned.txt
CCMSLIB00000070293 binned.txt
CCMSLIB00000070294 binned.txt
CCMSLIB00000070295 binned.txt
CCMSLIB00000070296 binned.txt
CCMSLIB00000070301 binned.txt
CCMSLIB00000070304 binned.txt
CCMSLIB000

CCMSLIB00000077998 binned.txt
CCMSLIB00000078000 binned.txt
CCMSLIB00000078001 binned.txt
CCMSLIB00000078003 binned.txt
CCMSLIB00000078005 binned.txt
CCMSLIB00000078006 binned.txt
CCMSLIB00000078007 binned.txt
CCMSLIB00000078008 binned.txt
CCMSLIB00000078009 binned.txt
CCMSLIB00000078010 binned.txt
CCMSLIB00000078011 binned.txt
CCMSLIB00000078014 binned.txt
CCMSLIB00000078015 binned.txt
CCMSLIB00000078016 binned.txt
CCMSLIB00000078017 binned.txt
CCMSLIB00000078018 binned.txt
CCMSLIB00000078019 binned.txt
CCMSLIB00000078020 binned.txt
CCMSLIB00000078021 binned.txt
CCMSLIB00000078022 binned.txt
CCMSLIB00000078023 binned.txt
CCMSLIB00000078024 binned.txt
CCMSLIB00000078025 binned.txt
CCMSLIB00000078026 binned.txt
CCMSLIB00000078027 binned.txt
CCMSLIB00000078028 binned.txt
CCMSLIB00000078030 binned.txt
CCMSLIB00000078031 binned.txt
CCMSLIB00000078032 binned.txt
CCMSLIB00000078034 binned.txt
CCMSLIB00000078035 binned.txt
CCMSLIB00000078036 binned.txt
CCMSLIB00000078037 binned.txt
CCMSLIB000

CCMSLIB00000078310 binned.txt
CCMSLIB00000078311 binned.txt
CCMSLIB00000078312 binned.txt
CCMSLIB00000078313 binned.txt
CCMSLIB00000078314 binned.txt
CCMSLIB00000078315 binned.txt
CCMSLIB00000078316 binned.txt
CCMSLIB00000078318 binned.txt
CCMSLIB00000078319 binned.txt
CCMSLIB00000078320 binned.txt
CCMSLIB00000078321 binned.txt
CCMSLIB00000078322 binned.txt
CCMSLIB00000078323 binned.txt
CCMSLIB00000078324 binned.txt
CCMSLIB00000078325 binned.txt
CCMSLIB00000078326 binned.txt
CCMSLIB00000078328 binned.txt
CCMSLIB00000078329 binned.txt
CCMSLIB00000078330 binned.txt
CCMSLIB00000078331 binned.txt
CCMSLIB00000078332 binned.txt
CCMSLIB00000078335 binned.txt
CCMSLIB00000078337 binned.txt
CCMSLIB00000078338 binned.txt
CCMSLIB00000078339 binned.txt
CCMSLIB00000078341 binned.txt
CCMSLIB00000078342 binned.txt
CCMSLIB00000078343 binned.txt
CCMSLIB00000078344 binned.txt
CCMSLIB00000078345 binned.txt
CCMSLIB00000078346 binned.txt
CCMSLIB00000078347 binned.txt
CCMSLIB00000078348 binned.txt
CCMSLIB000

CCMSLIB00000078644 binned.txt
CCMSLIB00000078645 binned.txt
CCMSLIB00000078646 binned.txt
CCMSLIB00000078647 binned.txt
CCMSLIB00000078648 binned.txt
CCMSLIB00000078650 binned.txt
CCMSLIB00000078651 binned.txt
CCMSLIB00000078652 binned.txt
CCMSLIB00000078653 binned.txt
CCMSLIB00000078668 binned.txt
CCMSLIB00000078679 binned.txt
CCMSLIB00000078680 binned.txt
CCMSLIB00000078681 binned.txt
CCMSLIB00000078683 binned.txt
CCMSLIB00000078684 binned.txt
CCMSLIB00000078685 binned.txt
CCMSLIB00000078686 binned.txt
CCMSLIB00000078687 binned.txt
CCMSLIB00000078688 binned.txt
CCMSLIB00000078689 binned.txt
CCMSLIB00000078690 binned.txt
CCMSLIB00000078691 binned.txt
CCMSLIB00000078692 binned.txt
CCMSLIB00000078693 binned.txt
CCMSLIB00000078694 binned.txt
CCMSLIB00000078695 binned.txt
CCMSLIB00000078696 binned.txt
CCMSLIB00000078697 binned.txt
CCMSLIB00000078698 binned.txt
CCMSLIB00000078699 binned.txt
CCMSLIB00000078700 binned.txt
CCMSLIB00000078701 binned.txt
CCMSLIB00000078702 binned.txt
CCMSLIB000

CCMSLIB00000079022 binned.txt
CCMSLIB00000079023 binned.txt
CCMSLIB00000079024 binned.txt
CCMSLIB00000079025 binned.txt
CCMSLIB00000079026 binned.txt
CCMSLIB00000079027 binned.txt
CCMSLIB00000079028 binned.txt
CCMSLIB00000079029 binned.txt
CCMSLIB00000079030 binned.txt
CCMSLIB00000079031 binned.txt
CCMSLIB00000079032 binned.txt
CCMSLIB00000079033 binned.txt
CCMSLIB00000079034 binned.txt
CCMSLIB00000079035 binned.txt
CCMSLIB00000079036 binned.txt
CCMSLIB00000079037 binned.txt
CCMSLIB00000079038 binned.txt
CCMSLIB00000079039 binned.txt
CCMSLIB00000079040 binned.txt
CCMSLIB00000079041 binned.txt
CCMSLIB00000079042 binned.txt
CCMSLIB00000079043 binned.txt
CCMSLIB00000079044 binned.txt
CCMSLIB00000079046 binned.txt
CCMSLIB00000079047 binned.txt
CCMSLIB00000079048 binned.txt
CCMSLIB00000079049 binned.txt
CCMSLIB00000079051 binned.txt
CCMSLIB00000079052 binned.txt
CCMSLIB00000079053 binned.txt
CCMSLIB00000079054 binned.txt
CCMSLIB00000079055 binned.txt
CCMSLIB00000079057 binned.txt
CCMSLIB000

CCMSLIB00000079405 binned.txt
CCMSLIB00000079406 binned.txt
CCMSLIB00000079407 binned.txt
CCMSLIB00000079408 binned.txt
CCMSLIB00000079409 binned.txt
CCMSLIB00000079410 binned.txt
CCMSLIB00000079411 binned.txt
CCMSLIB00000079412 binned.txt
CCMSLIB00000079413 binned.txt
CCMSLIB00000079414 binned.txt
CCMSLIB00000079415 binned.txt
CCMSLIB00000079416 binned.txt
CCMSLIB00000079417 binned.txt
CCMSLIB00000079418 binned.txt
CCMSLIB00000079419 binned.txt
CCMSLIB00000079420 binned.txt
CCMSLIB00000079421 binned.txt
CCMSLIB00000079422 binned.txt
CCMSLIB00000079423 binned.txt
CCMSLIB00000079424 binned.txt
CCMSLIB00000079425 binned.txt
CCMSLIB00000079427 binned.txt
CCMSLIB00000079428 binned.txt
CCMSLIB00000079429 binned.txt
CCMSLIB00000079430 binned.txt
CCMSLIB00000079431 binned.txt
CCMSLIB00000079432 binned.txt
CCMSLIB00000079433 binned.txt
CCMSLIB00000079434 binned.txt
CCMSLIB00000079435 binned.txt
CCMSLIB00000079436 binned.txt
CCMSLIB00000079437 binned.txt
CCMSLIB00000079438 binned.txt
CCMSLIB000

CCMSLIB00000079683 binned.txt
CCMSLIB00000079684 binned.txt
CCMSLIB00000079685 binned.txt
CCMSLIB00000079686 binned.txt
CCMSLIB00000079687 binned.txt
CCMSLIB00000079688 binned.txt
CCMSLIB00000079689 binned.txt
CCMSLIB00000079690 binned.txt
CCMSLIB00000079691 binned.txt
CCMSLIB00000079692 binned.txt
CCMSLIB00000079693 binned.txt
CCMSLIB00000079694 binned.txt
CCMSLIB00000079695 binned.txt
CCMSLIB00000079696 binned.txt
CCMSLIB00000079697 binned.txt
CCMSLIB00000079698 binned.txt
CCMSLIB00000079699 binned.txt
CCMSLIB00000079700 binned.txt
CCMSLIB00000079701 binned.txt
CCMSLIB00000079702 binned.txt
CCMSLIB00000079703 binned.txt
CCMSLIB00000079704 binned.txt
CCMSLIB00000079705 binned.txt
CCMSLIB00000079706 binned.txt
CCMSLIB00000079707 binned.txt
CCMSLIB00000079708 binned.txt
CCMSLIB00000079709 binned.txt
CCMSLIB00000079710 binned.txt
CCMSLIB00000079711 binned.txt
CCMSLIB00000079712 binned.txt
CCMSLIB00000079713 binned.txt
CCMSLIB00000079714 binned.txt
CCMSLIB00000079715 binned.txt
CCMSLIB000

CCMSLIB00000079969 binned.txt
CCMSLIB00000079970 binned.txt
CCMSLIB00000079971 binned.txt
CCMSLIB00000079972 binned.txt
CCMSLIB00000079973 binned.txt
CCMSLIB00000079974 binned.txt
CCMSLIB00000079975 binned.txt
CCMSLIB00000079977 binned.txt
CCMSLIB00000079978 binned.txt
CCMSLIB00000079979 binned.txt
CCMSLIB00000079980 binned.txt
CCMSLIB00000079981 binned.txt
CCMSLIB00000079982 binned.txt
CCMSLIB00000079983 binned.txt
CCMSLIB00000079984 binned.txt
CCMSLIB00000079985 binned.txt
CCMSLIB00000079986 binned.txt
CCMSLIB00000079987 binned.txt
CCMSLIB00000079988 binned.txt
CCMSLIB00000079989 binned.txt
CCMSLIB00000079990 binned.txt
CCMSLIB00000079991 binned.txt
CCMSLIB00000079992 binned.txt
CCMSLIB00000079993 binned.txt
CCMSLIB00000079994 binned.txt
CCMSLIB00000079995 binned.txt
CCMSLIB00000079996 binned.txt
CCMSLIB00000079997 binned.txt
CCMSLIB00000079998 binned.txt
CCMSLIB00000079999 binned.txt
CCMSLIB00000080000 binned.txt
CCMSLIB00000080001 binned.txt
CCMSLIB00000080002 binned.txt
CCMSLIB000

CCMSLIB00000080251 binned.txt
CCMSLIB00000080252 binned.txt
CCMSLIB00000080253 binned.txt
CCMSLIB00000080254 binned.txt
CCMSLIB00000080255 binned.txt
CCMSLIB00000080256 binned.txt
CCMSLIB00000080257 binned.txt
CCMSLIB00000080258 binned.txt
CCMSLIB00000080259 binned.txt
CCMSLIB00000080260 binned.txt
CCMSLIB00000080261 binned.txt
CCMSLIB00000080262 binned.txt
CCMSLIB00000080263 binned.txt
CCMSLIB00000080264 binned.txt
CCMSLIB00000080265 binned.txt
CCMSLIB00000080266 binned.txt
CCMSLIB00000080267 binned.txt
CCMSLIB00000080268 binned.txt
CCMSLIB00000080269 binned.txt
CCMSLIB00000080270 binned.txt
CCMSLIB00000080271 binned.txt
CCMSLIB00000080272 binned.txt
CCMSLIB00000080273 binned.txt
CCMSLIB00000080274 binned.txt
CCMSLIB00000080275 binned.txt
CCMSLIB00000080276 binned.txt
CCMSLIB00000080277 binned.txt
CCMSLIB00000080278 binned.txt
CCMSLIB00000080279 binned.txt
CCMSLIB00000080280 binned.txt
CCMSLIB00000080281 binned.txt
CCMSLIB00000080282 binned.txt
CCMSLIB00000080283 binned.txt
CCMSLIB000

CCMSLIB00000080531 binned.txt
CCMSLIB00000080532 binned.txt
CCMSLIB00000080533 binned.txt
CCMSLIB00000080534 binned.txt
CCMSLIB00000080535 binned.txt
CCMSLIB00000080536 binned.txt
CCMSLIB00000080537 binned.txt
CCMSLIB00000080538 binned.txt
CCMSLIB00000080539 binned.txt
CCMSLIB00000080540 binned.txt
CCMSLIB00000080541 binned.txt
CCMSLIB00000080542 binned.txt
CCMSLIB00000080543 binned.txt
CCMSLIB00000080544 binned.txt
CCMSLIB00000080545 binned.txt
CCMSLIB00000080546 binned.txt
CCMSLIB00000080547 binned.txt
CCMSLIB00000080548 binned.txt
CCMSLIB00000080549 binned.txt
CCMSLIB00000080550 binned.txt
CCMSLIB00000080551 binned.txt
CCMSLIB00000080552 binned.txt
CCMSLIB00000080553 binned.txt
CCMSLIB00000080554 binned.txt
CCMSLIB00000080555 binned.txt
CCMSLIB00000080556 binned.txt
CCMSLIB00000080557 binned.txt
CCMSLIB00000080558 binned.txt
CCMSLIB00000080559 binned.txt
CCMSLIB00000080560 binned.txt
CCMSLIB00000080561 binned.txt
CCMSLIB00000080562 binned.txt
CCMSLIB00000080563 binned.txt
CCMSLIB000

CCMSLIB00000084795 binned.txt
CCMSLIB00000084796 binned.txt
CCMSLIB00000084798 binned.txt
CCMSLIB00000084799 binned.txt
CCMSLIB00000084800 binned.txt
CCMSLIB00000084802 binned.txt
CCMSLIB00000084803 binned.txt
CCMSLIB00000084804 binned.txt
CCMSLIB00000084805 binned.txt
CCMSLIB00000084806 binned.txt
CCMSLIB00000084807 binned.txt
CCMSLIB00000084808 binned.txt
CCMSLIB00000084809 binned.txt
CCMSLIB00000084810 binned.txt
CCMSLIB00000084811 binned.txt
CCMSLIB00000084812 binned.txt
CCMSLIB00000084813 binned.txt
CCMSLIB00000084814 binned.txt
CCMSLIB00000084815 binned.txt
CCMSLIB00000084816 binned.txt
CCMSLIB00000084817 binned.txt
CCMSLIB00000084818 binned.txt
CCMSLIB00000084819 binned.txt
CCMSLIB00000084821 binned.txt
CCMSLIB00000084822 binned.txt
CCMSLIB00000084823 binned.txt
CCMSLIB00000084824 binned.txt
CCMSLIB00000084825 binned.txt
CCMSLIB00000084826 binned.txt
CCMSLIB00000084827 binned.txt
CCMSLIB00000084828 binned.txt
CCMSLIB00000084829 binned.txt
CCMSLIB00000084830 binned.txt
CCMSLIB000

CCMSLIB00000085107 binned.txt
CCMSLIB00000085108 binned.txt
CCMSLIB00000085109 binned.txt
CCMSLIB00000085110 binned.txt
CCMSLIB00000085112 binned.txt
CCMSLIB00000085113 binned.txt
CCMSLIB00000085114 binned.txt
CCMSLIB00000085115 binned.txt
CCMSLIB00000085116 binned.txt
CCMSLIB00000085117 binned.txt
CCMSLIB00000085118 binned.txt
CCMSLIB00000085119 binned.txt
CCMSLIB00000085120 binned.txt
CCMSLIB00000085121 binned.txt
CCMSLIB00000085122 binned.txt
CCMSLIB00000085123 binned.txt
CCMSLIB00000085124 binned.txt
CCMSLIB00000085126 binned.txt
CCMSLIB00000085128 binned.txt
CCMSLIB00000085129 binned.txt
CCMSLIB00000085130 binned.txt
CCMSLIB00000085131 binned.txt
CCMSLIB00000085132 binned.txt
CCMSLIB00000085133 binned.txt
CCMSLIB00000085136 binned.txt
CCMSLIB00000085137 binned.txt
CCMSLIB00000085138 binned.txt
CCMSLIB00000085139 binned.txt
CCMSLIB00000085140 binned.txt
CCMSLIB00000085141 binned.txt
CCMSLIB00000085142 binned.txt
CCMSLIB00000085143 binned.txt
CCMSLIB00000085144 binned.txt
CCMSLIB000

CCMSLIB00000085422 binned.txt
CCMSLIB00000085423 binned.txt
CCMSLIB00000085424 binned.txt
CCMSLIB00000085425 binned.txt
CCMSLIB00000085426 binned.txt
CCMSLIB00000085428 binned.txt
CCMSLIB00000085429 binned.txt
CCMSLIB00000085430 binned.txt
CCMSLIB00000085431 binned.txt
CCMSLIB00000085432 binned.txt
CCMSLIB00000085433 binned.txt
CCMSLIB00000085434 binned.txt
CCMSLIB00000085435 binned.txt
CCMSLIB00000085436 binned.txt
CCMSLIB00000085437 binned.txt
CCMSLIB00000085438 binned.txt
CCMSLIB00000085439 binned.txt
CCMSLIB00000085440 binned.txt
CCMSLIB00000085441 binned.txt
CCMSLIB00000085442 binned.txt
CCMSLIB00000085443 binned.txt
CCMSLIB00000085444 binned.txt
CCMSLIB00000085445 binned.txt
CCMSLIB00000085446 binned.txt
CCMSLIB00000085447 binned.txt
CCMSLIB00000085449 binned.txt
CCMSLIB00000085450 binned.txt
CCMSLIB00000085451 binned.txt
CCMSLIB00000085452 binned.txt
CCMSLIB00000085453 binned.txt
CCMSLIB00000085454 binned.txt
CCMSLIB00000085455 binned.txt
CCMSLIB00000085456 binned.txt
CCMSLIB000

CCMSLIB00000085719 binned.txt
CCMSLIB00000085720 binned.txt
CCMSLIB00000085721 binned.txt
CCMSLIB00000085722 binned.txt
CCMSLIB00000085723 binned.txt
CCMSLIB00000085724 binned.txt
CCMSLIB00000085725 binned.txt
CCMSLIB00000085726 binned.txt
CCMSLIB00000085727 binned.txt
CCMSLIB00000085728 binned.txt
CCMSLIB00000085729 binned.txt
CCMSLIB00000085731 binned.txt
CCMSLIB00000085732 binned.txt
CCMSLIB00000085733 binned.txt
CCMSLIB00000085734 binned.txt
CCMSLIB00000085735 binned.txt
CCMSLIB00000085736 binned.txt
CCMSLIB00000085737 binned.txt
CCMSLIB00000085738 binned.txt
CCMSLIB00000085739 binned.txt
CCMSLIB00000085740 binned.txt
CCMSLIB00000085741 binned.txt
CCMSLIB00000085742 binned.txt
CCMSLIB00000085743 binned.txt
CCMSLIB00000085744 binned.txt
CCMSLIB00000085746 binned.txt
CCMSLIB00000085747 binned.txt
CCMSLIB00000085748 binned.txt
CCMSLIB00000085749 binned.txt
CCMSLIB00000085750 binned.txt
CCMSLIB00000085751 binned.txt
CCMSLIB00000085752 binned.txt
CCMSLIB00000085753 binned.txt
CCMSLIB000

CCMSLIB00000086011 binned.txt
CCMSLIB00000086012 binned.txt
CCMSLIB00000086013 binned.txt
CCMSLIB00000086014 binned.txt
CCMSLIB00000086015 binned.txt
CCMSLIB00000086016 binned.txt
CCMSLIB00000086017 binned.txt
CCMSLIB00000086020 binned.txt
CCMSLIB00000086021 binned.txt
CCMSLIB00000086022 binned.txt
CCMSLIB00000086023 binned.txt
CCMSLIB00000086024 binned.txt
CCMSLIB00000086025 binned.txt
CCMSLIB00000086026 binned.txt
CCMSLIB00000086027 binned.txt
CCMSLIB00000086028 binned.txt
CCMSLIB00000086030 binned.txt
CCMSLIB00000086031 binned.txt
CCMSLIB00000086032 binned.txt
CCMSLIB00000086033 binned.txt
CCMSLIB00000086034 binned.txt
CCMSLIB00000086035 binned.txt
CCMSLIB00000086036 binned.txt
CCMSLIB00000086037 binned.txt
CCMSLIB00000086038 binned.txt
CCMSLIB00000086039 binned.txt
CCMSLIB00000086040 binned.txt
CCMSLIB00000086041 binned.txt
CCMSLIB00000086042 binned.txt
CCMSLIB00000086043 binned.txt
CCMSLIB00000086044 binned.txt
CCMSLIB00000086045 binned.txt
CCMSLIB00000086046 binned.txt
CCMSLIB000

CCMSLIB00000424835 binned.txt
CCMSLIB00000424837 binned.txt
CCMSLIB00000424840 binned.txt
CCMSLIB00000424841 binned.txt
CCMSLIB00000424842 binned.txt
CCMSLIB00000424843 binned.txt
CCMSLIB00000424844 binned.txt
CCMSLIB00000424846 binned.txt
CCMSLIB00000424847 binned.txt
CCMSLIB00000424848 binned.txt
CCMSLIB00000424849 binned.txt
CCMSLIB00000424850 binned.txt
CCMSLIB00000424851 binned.txt
CCMSLIB00000424853 binned.txt
CCMSLIB00000424856 binned.txt
CCMSLIB00000424857 binned.txt
CCMSLIB00000424858 binned.txt
CCMSLIB00000424859 binned.txt
CCMSLIB00000424860 binned.txt
CCMSLIB00000424861 binned.txt
CCMSLIB00000424862 binned.txt
CCMSLIB00000424863 binned.txt
CCMSLIB00000424864 binned.txt
CCMSLIB00000424865 binned.txt
CCMSLIB00000424867 binned.txt
CCMSLIB00000424870 binned.txt
CCMSLIB00000424871 binned.txt
CCMSLIB00000424872 binned.txt
CCMSLIB00000424873 binned.txt
CCMSLIB00000424874 binned.txt
CCMSLIB00000424875 binned.txt
CCMSLIB00000424876 binned.txt
CCMSLIB00000424877 binned.txt
CCMSLIB000

CCMSLIB00000478503 binned.txt
CCMSLIB00000478504 binned.txt
CCMSLIB00000478505 binned.txt
CCMSLIB00000478506 binned.txt
CCMSLIB00000478507 binned.txt
CCMSLIB00000478509 binned.txt
CCMSLIB00000478511 binned.txt
CCMSLIB00000478512 binned.txt
CCMSLIB00000478513 binned.txt
CCMSLIB00000478514 binned.txt
CCMSLIB00000478515 binned.txt
CCMSLIB00000478516 binned.txt
CCMSLIB00000478517 binned.txt
CCMSLIB00000478518 binned.txt
CCMSLIB00000478519 binned.txt
CCMSLIB00000478520 binned.txt
CCMSLIB00000478521 binned.txt
CCMSLIB00000478522 binned.txt
CCMSLIB00000478523 binned.txt
CCMSLIB00000478524 binned.txt
CCMSLIB00000478525 binned.txt
CCMSLIB00000478526 binned.txt
CCMSLIB00000478527 binned.txt
CCMSLIB00000478528 binned.txt
CCMSLIB00000478529 binned.txt
CCMSLIB00000478530 binned.txt
CCMSLIB00000478531 binned.txt
CCMSLIB00000478532 binned.txt
CCMSLIB00000478533 binned.txt
CCMSLIB00000478536 binned.txt
CCMSLIB00000478537 binned.txt
CCMSLIB00000478539 binned.txt
CCMSLIB00000478540 binned.txt
CCMSLIB000

CCMSLIB00000577674 binned.txt
CCMSLIB00000577675 binned.txt
CCMSLIB00000577677 binned.txt
CCMSLIB00000577678 binned.txt
CCMSLIB00000577680 binned.txt
CCMSLIB00000577681 binned.txt
CCMSLIB00000577682 binned.txt
CCMSLIB00000577683 binned.txt
CCMSLIB00000577684 binned.txt
CCMSLIB00000577685 binned.txt
CCMSLIB00000577688 binned.txt
CCMSLIB00000577691 binned.txt
CCMSLIB00000577692 binned.txt
CCMSLIB00000577693 binned.txt
CCMSLIB00000577695 binned.txt
CCMSLIB00000577696 binned.txt
CCMSLIB00000577697 binned.txt
CCMSLIB00000577700 binned.txt
CCMSLIB00000577701 binned.txt
CCMSLIB00000577703 binned.txt
CCMSLIB00000577704 binned.txt
CCMSLIB00000577705 binned.txt
CCMSLIB00000577706 binned.txt
CCMSLIB00000577708 binned.txt
CCMSLIB00000577709 binned.txt
CCMSLIB00000577712 binned.txt
CCMSLIB00000577713 binned.txt
CCMSLIB00000577715 binned.txt
CCMSLIB00000577717 binned.txt
CCMSLIB00000577718 binned.txt
CCMSLIB00000577719 binned.txt
CCMSLIB00000577720 binned.txt
CCMSLIB00000577721 binned.txt
CCMSLIB000

CCMSLIB00000579657 binned.txt
CCMSLIB00000579658 binned.txt
CCMSLIB00000579659 binned.txt
CCMSLIB00000579660 binned.txt
CCMSLIB00000579661 binned.txt
CCMSLIB00000579662 binned.txt
CCMSLIB00000579663 binned.txt
CCMSLIB00000579664 binned.txt
CCMSLIB00000579665 binned.txt
CCMSLIB00000579666 binned.txt
CCMSLIB00000579667 binned.txt
CCMSLIB00000579668 binned.txt
CCMSLIB00000579669 binned.txt
CCMSLIB00000579670 binned.txt
CCMSLIB00000579671 binned.txt
CCMSLIB00000579672 binned.txt
CCMSLIB00000579673 binned.txt
CCMSLIB00000579674 binned.txt
CCMSLIB00000579675 binned.txt
CCMSLIB00000579676 binned.txt
CCMSLIB00000579677 binned.txt
CCMSLIB00000579679 binned.txt
CCMSLIB00000579680 binned.txt
CCMSLIB00000579681 binned.txt
CCMSLIB00000579682 binned.txt
CCMSLIB00000579683 binned.txt
CCMSLIB00000579684 binned.txt
CCMSLIB00000579685 binned.txt
CCMSLIB00000579686 binned.txt
CCMSLIB00000579687 binned.txt
CCMSLIB00000579688 binned.txt
CCMSLIB00000579689 binned.txt
CCMSLIB00000579691 binned.txt
CCMSLIB000

In [4]:
print(main)
print(main.shape)
print(main.dtype)
print(np.amax(main))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(2995, 5770)
float64
1.0


In [5]:
print(np.count_nonzero(main, axis = 1).shape)
nonzeros = (np.count_nonzero(main, axis =1))
print(nonzeros)
#nonzeros = nonzeros[:, np.newaxis]
print(nonzeros)
print(nonzeros.shape)
#print(np.amax(nonzeros))
sum = len(np.where(nonzeros==0)[0])
print(len(np.where(nonzeros==0)[0]))
sum = sum + len(np.where(nonzeros==1)[0])
print(len(np.where(nonzeros==1)[0]))
sum = sum + len(np.where(nonzeros==2)[0])
print(len(np.where(nonzeros==2)[0]))
sum = sum + len(np.where(nonzeros==3)[0])
print(len(np.where(nonzeros==3)[0]))
sum = sum + len(np.where(nonzeros==4)[0])
print(len(np.where(nonzeros==4)[0]))

print(len(np.where(nonzeros<6)[0]))

print(sum)

print(np.where(nonzeros<5)[0])








(2995,)
[0 0 0 ... 0 1 0]
[0 0 0 ... 0 1 0]
(2995,)
788
190
42
9
4
1035
1033
[   0    1    2 ... 2992 2993 2994]


In [6]:
testmain = main
testmain = np.delete(testmain, np.where(nonzeros<5)[0], axis = 0)
print(testmain.shape)
nzero = (np.count_nonzero(testmain, axis =1))
print(len(np.where(nzero==0)[0]))

(1962, 5770)
0


In [7]:
maxVals = np.amax(testmain, axis=1)
print(maxVals[:10])
print(maxVals.shape)
print(len(np.where(maxVals<0.05)[0]))
testmain = np.delete(testmain, np.where(maxVals<0.05)[0], axis=0)
print(testmain.shape)
maxValsVerify = (np.amax(testmain, axis = 1))
print(len(np.where(maxValsVerify<0.05)[0]))

[0.18893188 0.00405051 0.24705882 0.33043478 0.44819277 0.28177413
 0.30429293 0.38986209 0.29345794 0.35903614]
(1962,)
283
(1679, 5770)
0


In [53]:
x_train = testmain 
x_train = x_train.reshape((1679, 5770))
print(x_train.shape[0])

inputLayer = Input(shape=x_train[0].shape)
l = inputLayer
l = Dense(256, activation='relu')(l)
l = Dense(128, activation='relu')(l)
l = Dense(16, activation='relu')(l)
l = Dense(2)(l)

latent_space = l

l2 = Dense(16, activation='relu')(l)
l2 = Dense(128,  activation='relu')(l2)
l2 = Dense(256,  activation='relu')(l2)
l2 = Dense(1679, activation='linear')(l2)

out_layer = l2

auto_model = Model(inputs = inputLayer, outputs = [out_layer, latent_space])

auto_model.compile(loss='mean_squared_error', optimizer = 'sgd')

auto_model.fit(x_train, batch_size=5000, shuffle=False, epochs=100)


1679


IndexError: list index out of range